events {}

http {

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 80;

    # Grafana
    location = /grafana {
      return 301 /grafana/;
    }

    location /grafana/ {
      proxy_pass http://grafana:3000;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Prefix /grafana;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    # Prometheus
    location /prometheus/ {
      proxy_pass http://prometheus:9090/;
      proxy_set_header Host $host;
    }

    # Portainer
    location /portainer/ {
      proxy_pass http://portainer:9000/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    # Dozzle
    location /dozzle/ {
      proxy_pass http://dozzle:8080/dozzle/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    # Default route
    location / {
      return 200 'NGINX is running';
      add_header Content-Type text/plain;
    }
  }
}
